### ISSUE TITLE
question of downstream finetun

### ISSUE THREAD

**Issue by zhr0313** [JUNJIE99/VISTA_Evaluation_FineTuning#10]
Hi,
When I wanted to do fine-tuning for downstream tasks, I found that there were no files in the corresponding paths in the code you provided.

sys.path.append('./FlagEmbedding/baai_general_embedding/downstream')

Moreover, the parameters in the "arguments" under "finetune" didn't match those in the bash file either.

class ModelArguments:
    """
    Arguments pertaining to which model/config/tokenizer we are going to fine-tune from.
    """

    model_name_or_path: str = field(
        metadata={"help": "Path to pretrained model or model identifier from huggingface.co/models"}
    )
    config_name: Optional[str] = field(
        default=None, metadata={"help": "Pretrained config name or path if not the same as model_name"}
    )
    tokenizer_name: Optional[str] = field(
        default=None, metadata={"help": "Pretrained tokenizer name or path if not the same as model_name"}
    )
    cache_dir: Optional[str] = field(
        default=None, metadata={"help": "Where do you want to store the pretrained models downloaded from s3"}
    )

full_options="
  --output_dir $SAVE_PATH \
  --bge_model_name_or_path  BAAI/bge-base-en-v1.5 \
  --visual_model_name_or_path  EVA02-CLIP-B-16 \
  --dataloader_num_workers 1  \
  --train_data $DATA_PATH \
  --train_data_image $IMAGE_PATH \
  --train_group_size $GROUP_SIZE
  --learning_rate $LR \
  --fp16 \
  --per_device_train_batch_size $BSZ_PERGPU \
  --dataloader_drop_last True \
  --normlized True \
  --temperature 0.02 \
  --logging_steps 10 \
  --num_train_epochs $EPOCH \
  --negatives_cross_device \
  --train_text_tower True  \
  --train_vision_tower True \
  --resume_path $RESUME_PATH \
  --save_steps $SAVE_STEPS \
  --deepspeed $DeepSpeedConfig \
  --gradient_checkpointing \

**Comment by JUNJIE99** [comment]
Hi, 

You need to first clone the [FlagEmbedding](https://github.com/FlagOpen/FlagEmbedding/tree/master/research/visual_bge) repository, which contains the original model files and inference code of VISTA (also known as Visualized BGE).

**Comment by zhr0313** [comment]
Hi,

I cloned FlagEmbedding, but the path sys.path.append('./FlagEmbedding/baai_general_embedding/downstream') in run_ds_cirr.py doesn't exist in the FlagEmbedding repository.  'Arguments' will result in an error.

**Comment by JUNJIE99** [comment]
Hi,

Since the FlagEmbedding repository has just been refactored, you only need to update to your current relative path (possibly `research/visual_bge/visual_bge`). Additionally, you need to place the relevant fine-tuning files in the `visual_bge` directory.

Regarding the arguments, I have just uploaded the corresponding file. If imported correctly, there should be no errors with the arguments.

**Comment by zhr0313** [comment]
OK,
I'll try it.
Thanks

**Comment by zhr0313** [comment]
By the way, could you please provide the requirements.txt with version?

**Comment by JUNJIE99** [comment]
> By the way, could you please provide the requirements.txt with version?

You can following this [link](https://github.com/FlagOpen/FlagEmbedding/tree/master/research/visual_bge#usage) for installation.

**Comment by zhr0313** [comment]
I have already followed the installation tutorial, but this error still occurred.

Traceback (most recent call last):
  File "/opt/tiger/mul_representation_reranker/backup/downstream_finetune_example/run_ds_cirr.py", line 171, in <module>
    main()
  File "/opt/tiger/mul_representation_reranker/backup/downstream_finetune_example/run_ds_cirr.py", line 163, in main
    trainer.train()
  File "/home/tiger/.local/lib/python3.9/site-packages/transformers/trainer.py", line 2123, in train
    return inner_training_loop(
  File "/home/tiger/.local/lib/python3.9/site-packages/transformers/trainer.py", line 2152, in _inner_training_loop
    train_dataloader = self.get_train_dataloader()
  File "/home/tiger/.local/lib/python3.9/site-packages/transformers/trainer.py", line 976, in get_train_dataloader
    return self.accelerator.prepare(DataLoader(train_dataset, **dataloader_params))
  File "/home/tiger/.local/lib/python3.9/site-packages/accelerate/accelerator.py", line 1284, in prepare
    if self.distributed_type == DistributedType.DEEPSPEED:
  File "/home/tiger/.local/lib/python3.9/site-packages/accelerate/accelerator.py", line 558, in distributed_type
    return self.state.distributed_type
  File "/home/tiger/.local/lib/python3.9/site-packages/accelerate/state.py", line 1125, in __getattr__
    raise AttributeError(
AttributeError: `AcceleratorState` object has no attribute `distributed_type`. This happens if `AcceleratorState._reset_state()` was called and an `Accelerator` or `PartialState` was not reinitialized.
 
And when I downgraded the version of the accelerate, there would be other errors instead.
